INSERT INTO Projects (Projectid, Title, Description, Studentid, Supervisorid, Status) VALUES
('1', 'AI-Powered Chatbot', 'Development of a chatbot using natural language processing and machine learning.', '1001', '2001', 'Proposed'),
('2', 'Renewable Energy Dashboard', 'A dashboard to monitor and analyze renewable energy production.', '1002', '2002', 'In Progress'),
('3', 'Wildlife Tracking System', 'IoT-based system for tracking wildlife movements in protected areas.', '1003', '2004', 'Completed'),
('4', 'Smart Irrigation Controller', 'Automated irrigation system using soil moisture sensors.', '1004', '2005', 'Proposed'),
('5', 'Mobile Health App', 'A mobile application for tracking personal health metrics.', '1006', '2006', 'In Progress'),
('6', 'Blockchain Voting Platform', 'Secure online voting platform using blockchain technology.', '1007', '2007', 'Completed'),
('7', 'E-Commerce Recommendation Engine', 'Personalized product recommendations for e-commerce users.', '1008', '2008', 'Proposed'),
('8', 'Autonomous Drone Delivery', 'System for autonomous delivery of packages using drones.', '1009', '2009', 'In Progress'),
('9', 'Virtual Reality Classroom', 'Immersive VR environment for remote education.', '1011', '2011', 'Completed'),
('10', 'Smart Home Security', 'AI-powered security system for smart homes.', '1012', '2012', 'Proposed'),
('11', 'Facial Recognition Attendance', 'Automated attendance system using facial recognition.', '1013', '2013', 'In Progress'),
('12', 'Online Exam Proctoring', 'Remote proctoring solution for online exams.', '1014', '2014', 'Completed'),
('13', 'Personal Finance Tracker', 'App for tracking expenses and managing personal finances.', '1015', '2015', 'Proposed'),
('14', 'Language Learning Platform', 'Interactive platform for learning new languages.', '1016', '2016', 'In Progress'),
('15', 'Smart Waste Management', 'IoT-based waste collection and management system.', '1017', '2017', 'Completed'),
('16', 'Automated Plant Disease Detection', 'Image-based detection of plant diseases using AI.', '1018', '2018', 'Proposed'),
('17', 'Remote Patient Monitoring', 'System for monitoring patient vitals remotely.', '1019', '2019', 'In Progress'),
('18', 'Digital Library System', 'Online platform for managing digital library resources.', '1021', '2021', 'Completed'),
('19', 'Traffic Prediction Model', 'Machine learning model for predicting city traffic.', '1022', '2022', 'Proposed'),
('20', 'Smart Parking Solution', 'Automated parking management using sensors.', '1023', '2023', 'In Progress'),
('21', 'Online Food Ordering System', 'Web-based platform for ordering food online.', '1024', '2024', 'Completed'),
('22', 'Fitness Tracker Wearable', 'Wearable device for tracking fitness activities.', '1025', '2025', 'Proposed'),
('23', 'Weather Forecasting App', 'Mobile app for accurate weather predictions.', '1026', '2026', 'In Progress'),
('24', 'E-Learning Content Generator', 'AI tool for generating e-learning content.', '1027', '2027', 'Completed'),
('25', 'Inventory Management System', 'Automated inventory tracking for small businesses.', '1028', '2028', 'Proposed'),
('26', 'Online Survey Platform', 'Platform for creating and analyzing online surveys.', '1029', '2029', 'In Progress'),
('27', 'Smart Lighting Control', 'Automated lighting system for energy savings.', '1011', '2011', 'Completed'),
('28', 'Digital Art Marketplace', 'Online marketplace for digital art and NFTs.', '1012', '2012', 'Proposed'),
('29', 'Remote Work Collaboration Tool', 'Tool for enhancing remote team collaboration.', '1013', '2013', 'In Progress'),
('30', 'Automated Resume Parser', 'AI-powered resume parsing and analysis tool.', '1014', '2014', 'Completed'),
('31', 'Online Tutoring Platform', 'Platform connecting students with tutors online.', '1015', '2015', 'Proposed'),
('32', 'Smart Thermostat', 'Intelligent thermostat for home energy management.', '1016', '2016', 'In Progress'),
('33', 'Crowdsourced Translation App', 'App for crowdsourcing translations in multiple languages.', '1017', '2017', 'Completed'),
('34', 'AI-Based Fraud Detection', 'Machine learning system for detecting financial fraud.', '1018', '2018', 'Proposed'),
('35', 'Virtual Museum Tour', 'VR tours of museums and art galleries.', '1019', '2019', 'In Progress'),
('36', 'Online Recipe Manager', 'App for storing and sharing recipes online.', '1021', '2021', 'Completed'),
('37', 'Smart Water Quality Monitor', 'IoT device for monitoring water quality.', '1022', '2022', 'Proposed'),
('38', 'Digital Event Ticketing', 'Online platform for event ticket sales.', '1023', '2023', 'In Progress'),
('39', 'AI-Powered News Aggregator', 'News aggregator using AI for personalized feeds.', '1024', '2024', 'Completed'),
('40', 'Remote Device Management', 'System for managing IoT devices remotely.', '1025', '2025', 'Proposed'),
('41', 'Online Portfolio Builder', 'Tool for creating professional online portfolios.', '1026', '2026', 'In Progress'),
('42', 'Smart Classroom Attendance', 'Automated attendance tracking in classrooms.', '1027', '2027', 'Completed'),
('43', 'Online Appointment Scheduler', 'Web-based appointment scheduling system.', '1028', '2028', 'Proposed'),
('44', 'AI-Based Medical Diagnosis', 'AI system for assisting medical diagnosis.', '1029', '2029', 'In Progress'),
('45', 'Digital Voting System', 'Secure digital voting platform for organizations.', '1011', '2011', 'Completed'),
('46', 'Online Bookstore', 'E-commerce platform for selling books online.', '1012', '2012', 'Proposed'),
('47', 'Smart Air Quality Sensor', 'IoT sensor for monitoring air quality.', '1013', '2013', 'In Progress'),
('48', 'Automated Expense Reporting', 'Tool for automating business expense reports.', '1014', '2014', 'Completed'),
('49', 'Online Language Exchange', 'Platform for language learners to connect and practice.', '1015', '2015', 'Proposed'),
('50', 'AI-Based Image Captioning', 'System for generating captions for images.', '1016', '2016', 'In Progress'),
('51', 'Remote Lab Experiment Platform', 'Online platform for conducting lab experiments remotely.', '1017', '2017', 'Completed'),
('52', 'Digital Marketing Analytics', 'Analytics tool for digital marketing campaigns.', '1018', '2018', 'Proposed'),
('53', 'Online Course Registration', 'System for registering for courses online.', '1019', '2019', 'In Progress'),
('54', 'Smart Fridge Inventory', 'IoT-based inventory management for smart fridges.', '1021', '2021', 'Completed'),
('55', 'Online Mental Health Support', 'Platform for mental health support and counseling.', '1022', '2022', 'Proposed'),
('56', 'AI-Based Stock Predictor', 'Machine learning model for predicting stock prices.', '1023', '2023', 'In Progress'),
('57', 'Digital Resume Builder', 'Tool for building digital resumes.', '1024', '2024', 'Completed'),
('58', 'Online Volunteer Management', 'Platform for managing volunteers for events.', '1025', '2025', 'Proposed'),
('59', 'Smart Traffic Light System', 'Automated traffic light control using sensors.', '1026', '2026', 'In Progress'),
('60', 'Online Donation Platform', 'Platform for managing charitable donations.', '1027', '2027', 'Completed'),
('61', 'AI-Based Sentiment Analysis', 'Tool for analyzing sentiment in social media posts.', '1028', '2028', 'Proposed'),
('62', 'Online Event Planner', 'Web-based event planning and management tool.', '1029', '2029', 'In Progress'),
('63', 'Smart Pet Feeder', 'Automated pet feeding system with mobile control.', '1011', '2011', 'Completed'),
('64', 'Digital Classroom Whiteboard', 'Interactive whiteboard for digital classrooms.', '1012', '2012', 'Proposed'),
('65', 'Remote Interview Platform', 'Platform for conducting remote job interviews.', '1013', '2013', 'In Progress'),
('66', 'Automated Document Scanner', 'AI-powered document scanning and organization.', '1014', '2014', 'Completed'),
('67', 'Online Study Group Finder', 'Tool for finding and joining study groups online.', '1015', '2015', 'Proposed'),
('68', 'Smart Bike Tracker', 'IoT device for tracking bike location and usage.', '1016', '2016', 'In Progress'),
('69', 'Crowdsourced News Platform', 'Platform for crowdsourcing and verifying news.', '1017', '2017', 'Completed'),
('70', 'AI-Based Disease Prediction', 'Machine learning model for predicting disease outbreaks.', '1018', '2018', 'Proposed'),
('71', 'Virtual Conference Platform', 'Online platform for hosting virtual conferences.', '1019', '2019', 'In Progress'),
('72', 'Online Recipe Sharing', 'Platform for sharing and discovering recipes.', '1021', '2021', 'Completed'),
('73', 'Smart Water Leak Detector', 'IoT device for detecting water leaks in homes.', '1022', '2022', 'Proposed'),
('74', 'Digital Ticket Scanner', 'Mobile app for scanning event tickets.', '1023', '2023', 'In Progress'),
('75', 'AI-Powered Content Moderator', 'AI system for moderating online content.', '1024', '2024', 'Completed'),
('76', 'Remote Device Troubleshooter', 'Tool for troubleshooting IoT devices remotely.', '1025', '2025', 'Proposed'),
('77', 'Online Resume Reviewer', 'Platform for reviewing and improving resumes.', '1026', '2026', 'In Progress'),
('78', 'Smart Classroom Scheduler', 'Automated scheduling for classrooms.', '1027', '2027', 'Completed'),
('79', 'Online Appointment Booking', 'Web-based appointment booking system.', '1028', '2028', 'Proposed'),
('80', 'AI-Based Health Risk Assessment', 'AI tool for assessing health risks.', '1029', '2029', 'In Progress'),
('81', 'Digital Voting Analytics', 'Analytics platform for digital voting data.', '1011', '2011', 'Completed'),
('82', 'Online Book Recommendation', 'System for recommending books online.', '1012', '2012', 'Proposed'),
('83', 'Smart Air Purifier', 'IoT-enabled air purifier with mobile control.', '1013', '2013', 'In Progress'),
('84', 'Automated Invoice Generator', 'Tool for generating invoices automatically.', '1014', '2014', 'Completed'),
('85', 'Online Language Tutor', 'Platform for connecting with language tutors.', '1015', '2015', 'Proposed'),
('86', 'AI-Based Image Search', 'System for searching images using AI.', '1016', '2016', 'In Progress'),
('87', 'Remote Science Lab', 'Online platform for remote science experiments.', '1017', '2017', 'Completed'),
('88', 'Digital Marketing Dashboard', 'Dashboard for tracking digital marketing metrics.', '1018', '2018', 'Proposed'),
('89', 'Online Course Scheduler', 'Tool for scheduling online courses.', '1019', '2019', 'In Progress'),
('90', 'Smart Kitchen Inventory', 'IoT-based inventory management for kitchens.', '1021', '2021', 'Completed'),
('91', 'Online Therapy Platform', 'Platform for online therapy and counseling.', '1022', '2022', 'Proposed'),
('92', 'AI-Based Investment Advisor', 'AI system for advising on investments.', '1023', '2023', 'In Progress'),
('93', 'Digital Portfolio Creator', 'Tool for creating digital portfolios.', '1024', '2024', 'Completed'),
('94', 'Online Volunteer Portal', 'Portal for managing volunteer opportunities.', '1025', '2025', 'Proposed'),
('95', 'Smart City Traffic Monitor', 'System for monitoring traffic in smart cities.', '1026', '2026', 'In Progress'),
('96', 'Online Charity Platform', 'Platform for managing charity events and donations.', '1027', '2027', 'Completed'),
('97', 'AI-Based Social Media Analytics', 'Analytics tool for social media data.', '1028', '2028', 'Proposed'),
('98', 'Online Event Registration', 'System for registering for events online.', '1029', '2029', 'In Progress'),
('99', 'Smart Pet Health Monitor', 'IoT device for monitoring pet health.', '1011', '2011', 'Completed'),
('100', 'Digital Classroom Scheduler', 'Tool for scheduling digital classroom activities.', '1012', '2012', 'Proposed'),
('101', 'Online Exam Scheduler', 'Platform for scheduling and managing online exams.', '1013', '2013', 'In Progress'),
('102', 'Automated Meeting Minutes', 'AI tool for generating meeting minutes from audio.', '1014', '2014', 'Completed'),
('103', 'Personal Budget Planner', 'App for planning and tracking personal budgets.', '1015', '2015', 'Proposed'),
('104', 'Language Pronunciation Coach', 'Interactive tool for improving language pronunciation.', '1016', '2016', 'In Progress'),
('105', 'Smart Recycling Bin', 'IoT-enabled recycling bin for waste sorting.', '1017', '2017', 'Completed'),
('106', 'Plant Growth Monitor', 'System for monitoring plant growth using sensors.', '1018', '2018', 'Proposed'),
('107', 'Remote Health Consultation', 'Platform for remote health consultations with doctors.', '1019', '2019', 'In Progress'),
('108', 'Digital Library Catalog', 'Online catalog for digital library resources.', '1021', '2021', 'Completed'),
('109', 'Traffic Flow Optimizer', 'AI model for optimizing urban traffic flow.', '1022', '2022', 'Proposed'),
('110', 'Smart Parking App', 'Mobile app for finding and reserving parking spots.', '1023', '2023', 'In Progress'),
('111', 'Online Grocery Delivery', 'Platform for ordering groceries online.', '1024', '2024', 'Completed'),
('112', 'Fitness Challenge Tracker', 'App for tracking fitness challenges and progress.', '1025', '2025', 'Proposed'),
('113', 'Weather Alert System', 'System for sending weather alerts to users.', '1026', '2026', 'In Progress'),
('114', 'E-Learning Quiz Generator', 'Tool for generating quizzes for e-learning.', '1027', '2027', 'Completed'),
('115', 'Inventory Forecasting Tool', 'AI tool for forecasting inventory needs.', '1028', '2028', 'Proposed'),
('116', 'Online Feedback Collector', 'Platform for collecting feedback from users.', '1029', '2029', 'In Progress'),
('117', 'Smart Home Lighting', 'Automated lighting control for smart homes.', '1011', '2011', 'Completed'),
('118', 'Digital Art Gallery', 'Online gallery for displaying digital art.', '1012', '2012', 'Proposed'),
('119', 'Remote Team Management', 'Tool for managing remote teams and projects.', '1013', '2013', 'In Progress'),
('120', 'Automated Job Application', 'Platform for automating job applications.', '1014', '2014', 'Completed'),
('121', 'Online Study Planner', 'App for planning and organizing study schedules.', '1015', '2015', 'Proposed'),
('122', 'Smart Thermostat Control', 'Mobile app for controlling smart thermostats.', '1016', '2016', 'In Progress'),
('123', 'Crowdsourced Dictionary', 'Platform for building a crowdsourced dictionary.', '1017', '2017', 'Completed'),
('124', 'AI-Based Loan Approval', 'Machine learning model for loan approval.', '1018', '2018', 'Proposed'),
('125', 'Virtual Museum Guide', 'Interactive guide for virtual museum tours.', '1019', '2019', 'In Progress'),
('126', 'Online Recipe Organizer', 'Tool for organizing and sharing recipes.', '1021', '2021', 'Completed'),
('127', 'Smart Water Usage Monitor', 'IoT device for monitoring water usage.', '1022', '2022', 'Proposed'),
('128', 'Digital Event Organizer', 'Platform for organizing digital events.', '1023', '2023', 'In Progress'),
('129', 'AI-Powered News Filter', 'AI tool for filtering news articles.', '1024', '2024', 'Completed'),
('130', 'Remote Device Updater', 'System for updating IoT devices remotely.', '1025', '2025', 'Proposed'),
('131', 'Online Portfolio Showcase', 'Platform for showcasing professional portfolios.', '1026', '2026', 'In Progress'),
('132', 'Smart Classroom Tools', 'Suite of tools for smart classrooms.', '1027', '2027', 'Completed'),
('133', 'Online Appointment Reminder', 'App for sending appointment reminders.', '1028', '2028', 'Proposed'),
('134', 'AI-Based Medical Imaging', 'AI system for analyzing medical images.', '1029', '2029', 'In Progress'),
('135', 'Digital Voting Records', 'System for storing digital voting records.', '1011', '2011', 'Completed'),
('136', 'Online Book Club', 'Platform for joining and managing book clubs.', '1012', '2012', 'Proposed'),
('137', 'Smart Air Monitoring', 'IoT system for monitoring air quality.', '1013', '2013', 'In Progress'),
('138', 'Automated Expense Tracker', 'App for tracking expenses automatically.', '1014', '2014', 'Completed'),
('139', 'Online Language Practice', 'Platform for practicing languages online.', '1015', '2015', 'Proposed'),
('140', 'AI-Based Image Tagging', 'System for tagging images using AI.', '1016', '2016', 'In Progress'),
('141', 'Remote Lab Management', 'Tool for managing remote laboratory activities.', '1017', '2017', 'Completed'),
('142', 'Digital Marketing Planner', 'Planner for digital marketing campaigns.', '1018', '2018', 'Proposed'),
('143', 'Online Course Finder', 'App for finding online courses.', '1019', '2019', 'In Progress'),
('144', 'Smart Fridge Monitor', 'IoT device for monitoring fridge contents.', '1021', '2021', 'Completed'),
('145', 'Online Mental Health Portal', 'Portal for mental health resources.', '1022', '2022', 'Proposed'),
('146', 'AI-Based Stock Analysis', 'AI tool for analyzing stock market data.', '1023', '2023', 'In Progress'),
('147', 'Digital Resume Templates', 'Collection of digital resume templates.', '1024', '2024', 'Completed'),
('148', 'Online Volunteer Scheduler', 'App for scheduling volunteer activities.', '1025', '2025', 'Proposed'),
('149', 'Smart Traffic Management', 'System for managing city traffic.', '1026', '2026', 'In Progress'),
('150', 'Online Charity Organizer', 'Platform for organizing charity events.', '1027', '2027', 'Completed'),
('151', 'AI-Based Social Analytics', 'Tool for analyzing social media trends.', '1028', '2028', 'Proposed'),
('152', 'Online Event Calendar', 'Calendar for managing event schedules.', '1029', '2029', 'In Progress'),
('153', 'Smart Pet Activity Tracker', 'IoT device for tracking pet activity.', '1011', '2011', 'Completed'),
('154', 'Digital Classroom Planner', 'Planner for digital classroom activities.', '1012', '2012', 'Proposed'),
('155', 'Remote Interview Scheduler', 'App for scheduling remote interviews.', '1013', '2013', 'In Progress'),
('156', 'Automated Document Organizer', 'Tool for organizing documents automatically.', '1014', '2014', 'Completed'),
('157', 'Online Study Group Scheduler', 'App for scheduling study group meetings.', '1015', '2015', 'Proposed'),
('158', 'Smart Bike Lock', 'IoT-enabled bike lock with mobile control.', '1016', '2016', 'In Progress'),
('159', 'Crowdsourced News Verification', 'Platform for verifying news articles.', '1017', '2017', 'Completed'),
('160', 'AI-Based Disease Monitoring', 'System for monitoring disease outbreaks.', '1018', '2018', 'Proposed'),
('161', 'Virtual Conference Scheduler', 'App for scheduling virtual conferences.', '1019', '2019', 'In Progress'),
('162', 'Online Recipe Rating', 'Platform for rating and reviewing recipes.', '1021', '2021', 'Completed'),
('163', 'Smart Water Leak Alert', 'IoT device for alerting water leaks.', '1022', '2022', 'Proposed'),
('164', 'Digital Ticket Management', 'System for managing digital tickets.', '1023', '2023', 'In Progress'),
('165', 'AI-Powered Content Filter', 'AI tool for filtering online content.', '1024', '2024', 'Completed'),
('166', 'Remote Device Diagnostics', 'Tool for diagnosing IoT device issues.', '1025', '2025', 'Proposed'),
('167', 'Online Resume Builder Pro', 'Advanced tool for building resumes.', '1026', '2026', 'In Progress'),
('168', 'Smart Classroom Attendance Pro', 'Enhanced attendance tracking for classrooms.', '1027', '2027', 'Completed'),
('169', 'Online Appointment Booking Pro', 'Advanced appointment booking system.', '1028', '2028', 'Proposed'),
('170', 'AI-Based Health Assessment Pro', 'Advanced AI tool for health assessment.', '1029', '2029', 'In Progress'),
('171', 'Digital Voting Analytics Pro', 'Advanced analytics for digital voting.', '1011', '2011', 'Completed'),
('172', 'Online Book Recommendation Pro', 'Advanced book recommendation system.', '1012', '2012', 'Proposed'),
('173', 'Smart Air Purifier Pro', 'Advanced IoT air purifier.', '1013', '2013', 'In Progress'),
('174', 'Automated Invoice Generator Pro', 'Advanced invoice generation tool.', '1014', '2014', 'Completed'),
('175', 'Online Language Tutor Pro', 'Advanced platform for language tutoring.', '1015', '2015', 'Proposed'),
('176', 'AI-Based Image Search Pro', 'Advanced image search using AI.', '1016', '2016', 'In Progress'),
('177', 'Remote Science Lab Pro', 'Advanced remote science lab platform.', '1017', '2017', 'Completed'),
('178', 'Digital Marketing Dashboard Pro', 'Advanced dashboard for marketing analytics.', '1018', '2018', 'Proposed'),
('179', 'Online Course Scheduler Pro', 'Advanced course scheduling tool.', '1019', '2019', 'In Progress'),
('180', 'Smart Kitchen Inventory Pro', 'Advanced kitchen inventory management.', '1021', '2021', 'Completed'),
('181', 'Online Therapy Platform Pro', 'Advanced online therapy platform.', '1022', '2022', 'Proposed'),
('182', 'AI-Based Investment Advisor Pro', 'Advanced AI investment advisor.', '1023', '2023', 'In Progress'),
('183', 'Digital Portfolio Creator Pro', 'Advanced digital portfolio creation tool.', '1024', '2024', 'Completed'),
('184', 'Online Volunteer Portal Pro', 'Advanced volunteer management portal.', '1025', '2025', 'Proposed'),
('185', 'Smart City Traffic Monitor Pro', 'Advanced smart city traffic monitoring.', '1026', '2026', 'In Progress'),
('186', 'Online Charity Platform Pro', 'Advanced charity management platform.', '1027', '2027', 'Completed'),
('187', 'AI-Based Social Media Analytics Pro', 'Advanced social media analytics tool.', '1028', '2028', 'Proposed'),
('188', 'Online Event Registration Pro', 'Advanced event registration system.', '1029', '2029', 'In Progress'),
('189', 'Smart Pet Health Monitor Pro', 'Advanced pet health monitoring device.', '1011', '2011', 'Completed'),
('190', 'Digital Classroom Scheduler Pro', 'Advanced classroom scheduling tool.', '1012', '2012', 'Proposed'),
('191', 'Online Exam Scheduler Pro', 'Advanced online exam scheduling platform.', '1013', '2013', 'In Progress'),
('192', 'Automated Meeting Minutes Pro', 'Advanced meeting minutes generation tool.', '1014', '2014', 'Completed'),
('193', 'Personal Budget Planner Pro', 'Advanced personal budget planning app.', '1015', '2015', 'Proposed'),
('194', 'Language Pronunciation Coach Pro', 'Advanced language pronunciation tool.', '1016', '2016', 'In Progress'),
('195', 'Smart Recycling Bin Pro', 'Advanced IoT recycling bin.', '1017', '2017', 'Completed'),
('196', 'Plant Growth Monitor Pro', 'Advanced plant growth monitoring system.', '1018', '2018', 'Proposed'),
('197', 'Remote Health Consultation Pro', 'Advanced remote health consultation platform.', '1019', '2019', 'In Progress'),
('198', 'Digital Library Catalog Pro', 'Advanced digital library catalog.', '1021', '2021', 'Completed'),
('199', 'Traffic Flow Optimizer Pro', 'Advanced urban traffic optimization model.', '1022', '2022', 'Proposed'),
('200', 'Smart Parking App Pro', 'Advanced smart parking mobile app.', '1023', '2023', 'In Progress');

COMMIT;
