INSERT INTO STUDENTS (STUDENTID, FULLNAME, EMAIL) VALUES
('1001', 'Alice Smith', 'alice.smith@example.com'),
('1002', 'Bob Johnson', 'bob.johnson@example.com'),
('1003', 'Charlie Lee', 'charlie.lee@example.com'),
('1004', 'Diana King', 'diana.king@example.com'),
('1005', 'Ethan Brown', 'ethan.brown@example.com'),
('1006', 'Fiona Clark', 'fiona.clark@example.com'),
('1007', 'George Miller', 'george.miller@example.com'),
('1008', 'Hannah Davis', 'hannah.davis@example.com'),
('1009', 'Ian Wilson', 'ian.wilson@example.com'),
('1010', 'Julia Moore', 'julia.moore@example.com'),
('1011', 'Kevin Taylor', 'kevin.taylor@example.com'),
('1012', 'Laura Anderson', 'laura.anderson@example.com'),
('1013', 'Michael Thomas', 'michael.thomas@example.com'),
('1014', 'Natalie Harris', 'natalie.harris@example.com'),
('1015', 'Oliver Martin', 'oliver.martin@example.com'),
('1016', 'Paula White', 'paula.white@example.com'),
('1017', 'Quentin Young', 'quentin.young@example.com'),
('1018', 'Rachel Scott', 'rachel.scott@example.com'),
('1019', 'Samuel Green', 'samuel.green@example.com'),
('1020', 'Tina Baker', 'tina.baker@example.com'),
('1021', 'Uma Carter', 'uma.carter@example.com'),
('1022', 'Victor Evans', 'victor.evans@example.com'),
('1023', 'Wendy Hall', 'wendy.hall@example.com'),
('1024', 'Xavier Lewis', 'xavier.lewis@example.com'),
('1025', 'Yvonne Perez', 'yvonne.perez@example.com'),
('1026', 'Zachary Reed', 'zachary.reed@example.com'),
('1027', 'Amber Price', 'amber.price@example.com'),
('1028', 'Brian Stewart', 'brian.stewart@example.com'),
('1029', 'Caitlin Turner', 'caitlin.turner@example.com'),
('1030', 'Derek Wood', 'derek.wood@example.com');

COMMIT;
