INSERT INTO SUPERVISORS VALUES
('2001', 'Dr. Alan Grant', 'alan.grant@example.com', 'Biology'),
('2002', 'Dr. Ellie Sattler', 'ellie.sattler@example.com', 'Botany'),
('2003', 'Dr. Ian Malcolm', 'ian.malcolm@example.com', 'Mathematics'),
('2004', 'Dr. Sarah Harding', 'sarah.harding@example.com', 'Zoology'),
('2005', 'Dr. Robert Burke', 'robert.burke@example.com', 'Paleontology'),
('2006', 'Dr. Henry Wu', 'henry.wu@example.com', 'Genetics'),
('2007', 'Dr. Gerry Harding', 'gerry.harding@example.com', 'Veterinary Science'),
('2008', 'Dr. Laura Murphy', 'laura.murphy@example.com', 'Physics'),
('2009', 'Dr. Mark Evans', 'mark.evans@example.com', 'Chemistry'),
('2010', 'Dr. Susan Black', 'susan.black@example.com', 'Computer Science'),
('2011', 'Dr. Peter Nash', 'peter.nash@example.com', 'Engineering'),
('2012', 'Dr. Karen Ross', 'karen.ross@example.com', 'Geology'),
('2013', 'Dr. David Bowman', 'david.bowman@example.com', 'Astronomy'),
('2014', 'Dr. Lisa Frank', 'lisa.frank@example.com', 'Psychology'),
('2015', 'Dr. Tom Carter', 'tom.carter@example.com', 'Sociology'),
('2016', 'Dr. Emily Stone', 'emily.stone@example.com', 'Anthropology'),
('2017', 'Dr. Brian Reed', 'brian.reed@example.com', 'Philosophy'),
('2018', 'Dr. Olivia King', 'olivia.king@example.com', 'Economics'),
('2019', 'Dr. Jack White', 'jack.white@example.com', 'Political Science'),
('2020', 'Dr. Megan Green', 'megan.green@example.com', 'History'),
('2021', 'Dr. Victor Hall', 'victor.hall@example.com', 'Linguistics'),
('2022', 'Dr. Rachel Scott', 'rachel.scott@example.com', 'Education'),
('2023', 'Dr. Samuel Lee', 'samuel.lee@example.com', 'Law'),
('2024', 'Dr. Wendy Clark', 'wendy.clark@example.com', 'Medicine'),
('2025', 'Dr. Xavier Lewis', 'xavier.lewis@example.com', 'Music'),
('2026', 'Dr. Yvonne Perez', 'yvonne.perez@example.com', 'Art'),
('2027', 'Dr. Zachary Reed', 'zachary.reed@example.com', 'Theatre'),
('2028', 'Dr. Amber Price', 'amber.price@example.com', 'Business'),
('2029', 'Dr. Brian Stewart', 'brian.stewart@example.com', 'Accounting'),
('2030', 'Dr. Caitlin Turner', 'caitlin.turner@example.com', 'Marketing');

COMMIT;
