CREATE OR REPLACE VIEW PROJECTVIEW AS
SELECT
    -- Project Details
    P.PROJECTID,
    P.TITLE AS PROJECTTITLE,
    P.DESCRIPTION AS PROJECTDESCRIPTION,
    P.STARTDATE AS PROJECTSTARTDATE,
    P.STATUS AS PROJECTSTATUS,
    -- Student Details
    S.STUDENTID,
    S.FULLNAME AS STUDENTFULLNAME,
    S.EMAIL AS STUDENTEMAIL,
    -- Supervisor Details (for the project)
    SUP.SUPERVISORID,
    SUP.FULLNAME AS SUPERVISORFULLNAME,
    SUP.EMAIL AS SUPERVISOREMAIL,
    SUP.DEPARTMENT AS SUPERVISORDEPARTMENT,
    -- Boolean indicating if the project has been evaluated or not
    E.GRADE AS PROJECTGRADE,
    -- Evaluation Details (if evaluated, else NULL)
    E.COMMENTS AS PROJECTFEEDBACK,
    MRK.SUPERVISORID AS MARKEDBYSUPERVISORID,
    -- Supervisor Details (person who marked the project)
    MRK.FULLNAME AS MARKEDBYSUPERVISORFULLNAME,
    MRK.EMAIL AS MARKEDBYSUPERVISOREMAIL,
    CASE
        WHEN E.PROJECTID IS NOT NULL THEN 'Yes'
        ELSE 'No'
    END AS ISEVALUATED
FROM
    PROJECTS P
INNER JOIN STUDENTS S ON P.STUDENTID = S.STUDENTID
INNER JOIN SUPERVISORS SUP ON P.SUPERVISORID = SUP.SUPERVISORID
-- Must be a left join since some projects may not have been evaluated yet
LEFT JOIN EVALUATIONS E ON P.PROJECTID = E.PROJECTID
LEFT JOIN SUPERVISORS MRK ON E.SUPERVISORID = MRK.SUPERVISORID;

COMMIT;
